# -*- coding: utf-8 -*-
"""lección2.1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12qbufsLktdBwfSHiVFgmrpakNtpY-sN1

Recomendador para un club de lectura juvenil
"""

import pandas as pd

# Define a list of 6 books by Latin American authors, each with title, author, genre, and mood.
books_data = [
    {'title': 'Papelucho', 'author': 'Marcela Paz', 'genre': 'Literatura infantil', 'mood': 'Humor'},
    {'title': 'Cien años de soledad', 'author': 'Gabriel García Márquez', 'genre': 'Realismo mágico', 'mood': 'Épica'},
    {'title': 'Rayuela', 'author': 'Julio Cortázar', 'genre': 'Novela experimental', 'mood': 'Intelectual'},
    {'title': 'La casa de los espíritus', 'author': 'Isabel Allende', 'genre': 'Realismo mágico', 'mood': 'Intriga'},
    {'title': 'Pedro Páramo', 'author': 'Juan Rulfo', 'genre': 'Novela gótica', 'mood': 'Misterio'},
    {'title': 'Como agua para chocolate', 'author': 'Laura Esquivel', 'genre': 'Realismo mágico', 'mood': 'Pasión'}
]
books_df = pd.DataFrame(books_data)
print("Usando lista de libros por defecto.")

def recommend_book(user_mood):
    """
    Recommends book titles based on the user's desired mood.

    Args:
        user_mood (str): The mood the user is looking for (e.g., 'Humor', 'Aventura').

    Returns:
        list: A list of dictionaries, where each dictionary represents a recommended book.
              Returns an empty list if no book matches the mood.
    """
    matching_books_df = books_df[books_df['mood'].str.lower() == user_mood.lower()]
    return matching_books_df.to_dict('records') # Convert DataFrame rows to list of dictionaries

# --- Demo de uso ---
while True:
    # Pide al usuario que ingrese un ánimo
    # Get all available moods to suggest to the user in the prompt
    available_moods_for_prompt = sorted(list(books_df['mood'].str.capitalize().unique()))
    anhelo_del_lector = input(f"¿Qué ánimo tienes hoy? (e.g., {', '.join(available_moods_for_prompt)}): ")

    # Obtiene la recomendación
    recommendations = recommend_book(anhelo_del_lector)

    # Imprime la recomendación(es)
    if recommendations:
        print("Te recomiendo los siguientes libros:")
        for book in recommendations:
            print(f"- {book['title']} (Autor: {book['author']}, Género: {book['genre']}, Ánimo: {book['mood']})")
    else:
        # Get all available moods to suggest to the user in the error message
        available_moods_for_error = sorted(list(books_df['mood'].str.capitalize().unique()))
        print(f"¡Ups! No encontré ningún libro para el ánimo '{anhelo_del_lector}'.")
        print(f"Pero no te desanimes, puedes probar con estos ánimos disponibles: {', '.join(available_moods_for_error)}.")

    # Preguntar al usuario si desea continuar
    continuar = input("¿Quieres buscar más recomendaciones? (s/n): ").lower()
    if continuar != 's':
        print("¡Gracias por usar el recomendador de libros!")
        break

"""La lógica de este recomendador guarda una lista de libros, cada uno con un 'ánimo' asociado. Cuando el usuario introduce un 'ánimo', el sistema busca en la lista el primer libro que coincida. Finalmente, devuelve el título de ese libro como recomendación."""